sudo: required
services:
  - docker

before_install:
  - docker build -t reallukemartin/reactdocker -f Dockerfile.dev .

script:
  - docker run reallukemartin/reactdocker npm run ci-test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "reactdocker"
  env: "Reactdocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-425305670341"
  bucket_path: "reactdocker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"